name: CI

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
      - releases/*

  pull_request:
    branches:
      - master

jobs:
  #==========================================================================
  # Primary builds
  #==========================================================================

  ubuntu-x86-64:
    name: Ubuntu cross (GCC, mingw-w64 runtime, MSVCRT, x86-64)
    runs-on: ubuntu-26.04

    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: >-
             sudo apt-get update ;
             sudo apt-get purge mono-runtime ;
             sudo apt-get install -y --no-install-recommends
             mingw-w64-x86-64-dev {gcc,g++,binutils}-mingw-w64-x86-64 meson
             ninja-build python3-pip wine wine-binfmt

      - name: Warming Wine up
        run: >-
             mkdir ~/.wine &&
             /usr/lib/x86_64-linux-gnu/wine/wineserver -p &&
             wine wineboot

      - name: Configure
        run: >-
             meson setup -Ddebug=true -Doptimization=s build_ci
             --prefix $PWD/build_pkg
             --cross-file cross/gcc.x86_64-w64-mingw32

      - name: Build
        run: meson compile -Cbuild_ci

      - name: Run tests
        run: meson test -t2 -Cbuild_ci --print-errorlogs

  msys2-ucrt64:
    name: MSYS2 native (GCC, mingw-w64 runtime, UCRT, x86-64)
    runs-on: windows-2022

    defaults:
      run: { shell: 'msys2 {0}' }

    steps:
      - uses: actions/checkout@v6

      - uses: msys2/setup-msys2@v2
        with: { msystem: UCRT64 }

      - name: Install dependencies
        run: >-
             pacman -Sy ;
             pacman -S --needed --noconfirm
             mingw-w64-ucrt-x86_64-{headers,crt,gcc,meson}

      - name: Configure
        run: >-
             meson setup -Ddebug=true -Doptimization=s build_ci
             --prefix $PWD/build_pkg

      - name: Build
        run: meson compile -Cbuild_ci

      - name: Run tests
        run: meson test -t2 -Cbuild_ci --print-errorlogs

      - name: Install
        run: meson install -Cbuild_ci --strip

      - uses: actions/upload-artifact@v7
        with: { path: build_pkg, name: 'x86-64_mingw-w64_gcc' }

  msys2-mingw32:
    name: MSYS2 native (GCC, mingw-w64 runtime, MSVCRT, x86-32)
    runs-on: windows-2022

    defaults:
      run: { shell: 'msys2 {0}' }

    steps:
      - uses: actions/checkout@v6

      - uses: msys2/setup-msys2@v2
        with: { msystem: MINGW32 }

      - name: Install dependencies
        run: >-
             pacman -Sy ;
             pacman -S --needed --noconfirm
             mingw-w64-i686-{headers,crt,gcc,meson,ninja}

      - name: Configure
        run: >-
             meson setup -Ddebug=true -Doptimization=s build_ci
             --prefix $PWD/build_pkg

      - name: Build
        run: meson compile -Cbuild_ci

      - name: Run tests
        run: meson test -t2 -Cbuild_ci --print-errorlogs

      - name: Install
        run: meson install -Cbuild_ci --strip

      - uses: actions/upload-artifact@v7
        with: { path: build_pkg, name: 'x86-32_mingw-w64_gcc' }

  #==========================================================================
  # Secondary builds
  #==========================================================================

  msys2-clang64:
    name: MSYS2 native (Clang, mingw-w64 runtime, UCRT, x86-64)
    runs-on: windows-2022

    defaults:
      run: { shell: 'msys2 {0}' }

    steps:
      - uses: actions/checkout@v6

      - uses: msys2/setup-msys2@v2
        with: { msystem: CLANG64 }

      - name: Install dependencies
        run: >-
             pacman -Sy ;
             pacman -S --needed --noconfirm
             mingw-w64-clang-x86_64-{headers,crt,clang,meson,ninja}

      - name: Configure
        run: >-
             meson setup -Ddebug=true -Doptimization=s build_ci
             --prefix $PWD/build_pkg

      - name: Build
        run: meson compile -Cbuild_ci

      - name: Run tests
        run: meson test -t2 -Cbuild_ci --print-errorlogs

      - name: Install
        run: meson install -Cbuild_ci --strip

      - uses: actions/upload-artifact@v7
        with: { path: build_pkg, name: 'x86-64_mingw-w64_clang' }

  msys2-clangarm64:
    name: MSYS2 native (Clang, mingw-w64 runtime, UCRT, ARM64)
    runs-on: windows-11-arm

    defaults:
      run: { shell: 'msys2 {0}' }

    steps:
      - uses: actions/checkout@v6

      - uses: msys2/setup-msys2@v2
        with: { msystem: CLANGARM64 }

      - name: Install dependencies
        run: >-
             pacman -Sy ;
             pacman -S --needed --noconfirm
             mingw-w64-clang-aarch64-{headers,crt,clang,meson,ninja}

      - name: Configure
        run: >-
             meson setup -Ddebug=true -Doptimization=s build_ci
             --prefix $PWD/build_pkg

      - name: Build
        run: meson compile -Cbuild_ci

      - name: Run tests
        run: meson test -t2 -Cbuild_ci --print-errorlogs

      - name: Install
        run: meson install -Cbuild_ci --strip

      - uses: actions/upload-artifact@v7
        with: { path: build_pkg, name: 'arm64_mingw-w64_clang' }

  llvm-mingw-arm64:
    name: LLVM-MinGW cross (Clang, mingw-w64 runtime, UCRT, ARM64)
    runs-on: ubuntu-24.04-arm
    container: ghcr.io/mstorsjo/wine

    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: >-
             sudo apt-get update ;
             sudo apt-get purge mono-runtime ;
             sudo apt-get install -y --no-install-recommends
             wget ninja-build python3-pip wine wine-binfmt &&
             sudo PIP_BREAK_SYSTEM_PACKAGES=1 pip3 install meson

      - name: Download LLVM MinGW
        run: >-
             wget 'https://github.com/mstorsjo/llvm-mingw/releases/download/20260602/llvm-mingw-20260602-ucrt-ubuntu-22.04-aarch64.tar.xz' &&
             tar -xaf llvm-mingw-20260602-ucrt-ubuntu-22.04-aarch64.tar.xz &&
             readlink -fe llvm-mingw-20260602-ucrt-ubuntu-22.04-aarch64/bin | tee -a "${GITHUB_PATH}"

      - name: Warming Wine up
        run: >-
             mkdir ~/.wine &&
             WINEPREFIX=${HOME}/.wine /usr/lib/wine/wineserver64 -p &&
             wine wineboot

      - name: Configure
        run: >-
             meson setup -Ddebug=true -Doptimization=s build_ci
             --prefix $PWD/build_pkg
             --cross-file cross/llvm.aarch64-w64-mingw32

      - name: Build
        run:  meson compile -Cbuild_ci

      - name: Run tests
        run: meson test -t20 -Cbuild_ci --print-errorlogs

  llvm-mingw-i686:
    name: LLVM-MinGW native (Clang, mingw-w64 runtime, UCRT, x86-32)
    runs-on: windows-2022

    defaults:
      run: { shell: pwsh }

    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: >-
             pip3 install --break-system-packages meson unzip

      - name: Download LLVM MinGW
        run: >-
             curl.exe -LO "https://github.com/mstorsjo/llvm-mingw/releases/download/20260602/llvm-mingw-20260602-ucrt-i686.zip" &&
             unzip llvm-mingw-20260602-ucrt-i686.zip &&
             cvpa llvm-mingw-20260602-ucrt-i686/bin | tee -a "${env:GITHUB_PATH}"

      - name: Configure
        run: >-
             meson setup -Ddebug=true -Doptimization=s build_ci
             --prefix $PWD/build_pkg
             --native-file cross/llvm.i686-w64-mingw32 -Denable-gc-sections=false

      - name: Build
        run: meson compile -Cbuild_ci

      - name: Run tests
        run: meson test -t2 -Cbuild_ci --print-errorlogs

      - name: Install
        run: meson install -Cbuild_ci --strip

      - uses: actions/upload-artifact@v7
        with: { path: build_pkg, name: 'x86-32_mingw-w64_clang' }

  llvm-mingw-arm64ec:
    name: LLVM-MinGW native (Clang, mingw-w64 runtime, UCRT, ARM64EC)
    runs-on: windows-11-arm

    defaults:
      run: { shell: pwsh }

    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: >-
             pip3 install --break-system-packages meson unzip

      - name: Download LLVM MinGW
        run: >-
             curl.exe -LO "https://github.com/mstorsjo/llvm-mingw/releases/download/20260602/llvm-mingw-20260602-ucrt-aarch64.zip" &&
             unzip llvm-mingw-20260602-ucrt-aarch64.zip &&
             cvpa llvm-mingw-20260602-ucrt-aarch64/bin | tee -a "${env:GITHUB_PATH}"

      - name: Configure
        run: >-
             meson setup -Ddebug=true -Doptimization=s build_ci
             --prefix $PWD/build_pkg
             --native-file cross/llvm.arm64ec-w64-mingw32 -Denable-gc-sections=false

      - name: Build
        run: meson compile -Cbuild_ci

      - name: Run tests
        run: meson test -t2 -Cbuild_ci --print-errorlogs

      - name: Configure emulated x64
        run: >-
             meson setup -Ddebug=true -Doptimization=s build_x64
             --native-file cross/llvm.x86_64-w64-mingw32

      - name: Build emulated x64
        run: meson compile -Cbuild_x64

      - name: Run emulated x64 tests
        run: meson test -t2 -Cbuild_x64 --print-errorlogs

      - name: Run emulated x64 tests, linking against ARM64EC
        run: >-
             copy build_ci/bin/*.dll build_x64/bin/ &&
             meson test -t2 -Cbuild_x64 --no-rebuild --print-errorlogs

      - name: Install
        run: meson install -Cbuild_ci --strip

      - uses: actions/upload-artifact@v7
        with: { path: build_pkg, name: 'arm64ec_mingw-w64_clang' }

  llvm-msvc-x64:
    name: LLVM-MSVC native (Clang, MSVC runtime, UCRT, x86-64)
    runs-on: windows-2022

    defaults:
      run: { shell: pwsh }

    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: >-
             pip3 install --break-system-packages meson

      - name: Configure
        run: >-
             meson setup -Ddebug=true -Doptimization=s build_ci
             --prefix $PWD/build_pkg
             --native-file cross/llvm-windows.x86_64-pc-windows-msvc

      - name: Build
        run: meson compile -Cbuild_ci

      - name: Run tests
        run: meson test -t2 -Cbuild_ci --print-errorlogs

      - name: Install
        run: meson install -Cbuild_ci --strip

      - uses: actions/upload-artifact@v7
        with: { path: build_pkg, name: 'x86-64_msvc_clang' }

  llvm-msvc-x86:
    name: LLVM-MSVC native (Clang, MSVC runtime, UCRT, x86-32)
    runs-on: windows-2022

    defaults:
      run: { shell: pwsh }

    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: >-
             pip3 install --break-system-packages meson

      - name: Configure
        run: >-
             meson setup -Ddebug=true -Doptimization=s build_ci
             --prefix $PWD/build_pkg
             --native-file cross/llvm-windows.i686-pc-windows-msvc

      - name: Build
        run: meson compile -Cbuild_ci

      - name: Run tests
        run: meson test -t2 -Cbuild_ci --print-errorlogs

      - name: Install
        run: meson install -Cbuild_ci --strip

      - uses: actions/upload-artifact@v7
        with: { path: build_pkg, name: 'x86-32_msvc_clang' }

  llvm-msvc-arm64:
    name: LLVM-MSVC native (Clang, MSVC runtime, UCRT, ARM64)
    runs-on: windows-11-arm

    defaults:
      run: { shell: pwsh }

    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: >-
             pip3 install --break-system-packages meson

      - name: Configure
        run: >-
             meson setup -Ddebug=true -Doptimization=s build_ci
             --prefix $PWD/build_pkg
             --native-file cross/llvm-windows.aarch64-pc-windows-msvc

      - name: Build
        run: meson compile -Cbuild_ci

      - name: Run tests
        run: meson test -t2 -Cbuild_ci --print-errorlogs

      - name: Install
        run: meson install -Cbuild_ci --strip

      - uses: actions/upload-artifact@v7
        with: { path: build_pkg, name: 'arm64_msvc_clang' }

  llvm-msvc-arm64ec:
    name: LLVM-MSVC native (Clang, MSVC runtime, UCRT, ARM64EC)
    runs-on: windows-11-arm

    defaults:
      run: { shell: pwsh }

    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: >-
             pip3 install --break-system-packages meson

      - name: Configure
        run: >-
             meson setup -Ddebug=true -Doptimization=s build_ci
             --prefix $PWD/build_pkg
             --native-file cross/llvm-windows.arm64ec-pc-windows-msvc

      - name: Build
        run: meson compile -Cbuild_ci

      - name: Run tests
        run: meson test -t2 -Cbuild_ci --print-errorlogs

      - name: Configure emulated x64
        run: >-
             meson setup -Ddebug=true -Doptimization=s build_x64
             --native-file cross/llvm-windows.x86_64-pc-windows-msvc

      - name: Build emulated x64
        run: meson compile -Cbuild_x64

      - name: Run emulated x64 tests
        run: meson test -t2 -Cbuild_x64 --print-errorlogs

      - name: Run emulated x64 tests, linking against ARM64EC
        run: >-
             copy build_ci/bin/*.dll build_x64/bin/ &&
             meson test -t2 -Cbuild_x64 --no-rebuild --print-errorlogs

      - name: Install
        run: meson install -Cbuild_ci --strip

      - uses: actions/upload-artifact@v7
        with: { path: build_pkg, name: 'arm64ec_msvc_clang' }

  #==========================================================================
  # Tertiary builds
  #==========================================================================

  msys2-msys:
    name: MSYS2 native (GCC, Cygwin/MSYS2 runtime, x86-64)
    runs-on: windows-2022

    defaults:
      run: { shell: 'msys2 {0}' }

    steps:
      - uses: actions/checkout@v6

      - uses: msys2/setup-msys2@v2
        with: { msystem: MSYS }

      - name: Install dependencies
        run: >-
             pacman -Sy ;
             pacman -S --needed --noconfirm
             msys2-{w32api-headers,runtime-devel} gcc meson

      - name: Configure
        run: >-
             meson setup -Ddebug=true -Doptimization=s build_ci
             --prefix $PWD/build_pkg

      - name: Build
        run: meson compile -Cbuild_ci

      - name: Run tests
        run: meson test -t2 -Cbuild_ci --print-errorlogs
